# Generated by Django 4.1.4 on 2022-12-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_filed', models.CharField(max_length=50)),
            ],
        ),
    ]
