# Generated by Django 4.1.4 on 2022-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodemo', '0002_static_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_informations',
            name='colour',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
    ]
