# Generated by Django 4.1.4 on 2022-12-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodemo', '0003_static_informations_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_informations',
            name='text_alingment',
            field=models.CharField(default='center', max_length=50),
        ),
    ]
