# Generated by Django 4.1.4 on 2022-12-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodemo', '0004_static_informations_text_alingment'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_informations',
            name='inputtype',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
