# Generated by Django 4.1.4 on 2022-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodemo', '0005_static_informations_inputtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_informations',
            name='data_of_filed1',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
